# This file was generated by GoReleaser. DO NOT EDIT.
cask "gongctl" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "c171cd48da3632da9f9f38a82301e2dfb242bd595193f92ba338774b35f85c68"
      url "https://github.com/JungHoonGhae/gongctl/releases/download/v#{version}/gongctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "faa889bfb31e29997c0785f2cd8843e9c1a39501e5fff7c349e24a76526bab51"
      url "https://github.com/JungHoonGhae/gongctl/releases/download/v#{version}/gongctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4769103b071b8ac8fb4af5925bc3677743dddd5315c53e762641d7b445878fd7"
      url "https://github.com/JungHoonGhae/gongctl/releases/download/v#{version}/gongctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a46217753953196e3fe090c2c199653e2d950350b65217f861333c6b4e3567cc"
      url "https://github.com/JungHoonGhae/gongctl/releases/download/v#{version}/gongctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gongctl"
  desc "data.go.kr 활용신청·인증키 발급·API 호출을 AI 에이전트가 대신 — 포털 UI를 사람이 건드릴 필요 없이"
  homepage "https://github.com/JungHoonGhae/gongctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gongctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gongctl"]
    end
  end

  # No zap stanza required

end
