# This file was generated by GoReleaser. DO NOT EDIT.
cask "gongctl" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "6ce28b9076eaf83c7c28b5b97c488efb2d7cbb674a6c4af0f8b8be3290369b9c"
      url "https://github.com/JungHoonGhae/gongctl/releases/download/v#{version}/gongctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "98b4edb51f8601f1d0d8c9017220db6abb965d2197f960781eb5521891f7db4f"
      url "https://github.com/JungHoonGhae/gongctl/releases/download/v#{version}/gongctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d611b4053a9484b23e394883c605c390e5b4c01ef9bf88bb53e2aef8876546b9"
      url "https://github.com/JungHoonGhae/gongctl/releases/download/v#{version}/gongctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "468bde0ffd7efda168f150f354e3d47d4712a235211d6a34f3bc2cee2ac7549d"
      url "https://github.com/JungHoonGhae/gongctl/releases/download/v#{version}/gongctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gongctl"
  desc "data.go.kr 활용신청·인증키 발급·API 호출을 AI 에이전트가 대신 — 포털 UI를 사람이 건드릴 필요 없이"
  homepage "https://github.com/JungHoonGhae/gongctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gongctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gongctl"]
    end
  end

  # No zap stanza required

end
