# This file was generated by GoReleaser. DO NOT EDIT.
cask "gongctl" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "e856bc534c9e5747ffcc40e24e410a6693f9de5700c52ab12cf5f130dddbeb61"
      url "https://github.com/JungHoonGhae/gongctl/releases/download/v#{version}/gongctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d57a79e5926edeb77593cd301da46f77940b7642e89795e7c765bcab4016dd6c"
      url "https://github.com/JungHoonGhae/gongctl/releases/download/v#{version}/gongctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7619ef6364bd43e6ebfde34929a333db0d60032c7d0160ef8bd83b77db2ae886"
      url "https://github.com/JungHoonGhae/gongctl/releases/download/v#{version}/gongctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dfae02619548f4d23c7fdbe892ad425c16e3bdd0dce8883ee320ae9a2759e05d"
      url "https://github.com/JungHoonGhae/gongctl/releases/download/v#{version}/gongctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gongctl"
  desc "data.go.kr 활용신청·인증키 발급·API 호출을 AI 에이전트가 대신 — 포털 UI를 사람이 건드릴 필요 없이"
  homepage "https://github.com/JungHoonGhae/gongctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gongctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gongctl"]
    end
  end

  # No zap stanza required

end
