# This file was generated by GoReleaser. DO NOT EDIT.
cask "opendatactl" do
  version "0.10.0"

  on_macos do
    on_arm do
      sha256 "078087c2fe896eefe47c2e4aadcf32a3257beac44a38de62fb766075b0795793"
      url "https://github.com/JungHoonGhae/opendatactl/releases/download/v#{version}/opendatactl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8f51f2ab3b3a2a5c3d97b2829226439362bd03def701cda7d690acc407fe0cda"
      url "https://github.com/JungHoonGhae/opendatactl/releases/download/v#{version}/opendatactl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1f70fd95bf0ae2771420ef17547d7c3b3e4e72dd9fa62e52ec28def532c3957f"
      url "https://github.com/JungHoonGhae/opendatactl/releases/download/v#{version}/opendatactl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d5397deddeff1eec3022dd74fdfef17ceb35370ff1917958a628c134c8b96fa0"
      url "https://github.com/JungHoonGhae/opendatactl/releases/download/v#{version}/opendatactl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "opendatactl"
  desc "data.go.kr 자연어 탐색부터 활용신청·승인 확인·실제 API 호출까지 잇는 AI 에이전트 워크플로"
  homepage "https://github.com/JungHoonGhae/opendatactl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "opendatactl"
  binary "gongctl"

  postflight do
    if OS.mac?
      ["opendatactl", "gongctl"].each do |binary|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{binary}"]
      end
    end
  end

  # No zap stanza required
end
