# This file was generated by GoReleaser. DO NOT EDIT.
cask "opendatactl" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "6ca85ba9862ea4e39d8b74b8e67f87aa2c9f105bc8652b3248b92e7c66f73b7f"
      url "https://github.com/JungHoonGhae/opendatactl/releases/download/v#{version}/opendatactl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0245419a37408b4063826c311a7d4407a223a5183baa7b725e72e03f1c0b8046"
      url "https://github.com/JungHoonGhae/opendatactl/releases/download/v#{version}/opendatactl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f5c873efb740571396c947a53e749851f60bd8eeb3ac137669da8c1052edc8ab"
      url "https://github.com/JungHoonGhae/opendatactl/releases/download/v#{version}/opendatactl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "53183fa6cac6afd2faa78b7bdcad428a7510f4a2bf241300b5043c5822852817"
      url "https://github.com/JungHoonGhae/opendatactl/releases/download/v#{version}/opendatactl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "opendatactl"
  desc "data.go.kr 자연어 탐색부터 활용신청·승인 확인·실제 API 호출까지 잇는 AI 에이전트 워크플로"
  homepage "https://github.com/JungHoonGhae/opendatactl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "opendatactl"
  binary "gongctl"

  postflight do
    if OS.mac?
      ["opendatactl", "gongctl"].each do |binary|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{binary}"]
      end
    end
  end

  # No zap stanza required
end
