# This file was generated by GoReleaser. DO NOT EDIT.
cask "opendatactl" do
  version "0.11.0"

  on_macos do
    on_arm do
      sha256 "1c6fcadec3c23b458f2d17fdda88272355796c38b3d78bc8e72e8ae8d5d54140"
      url "https://github.com/JungHoonGhae/opendatactl/releases/download/v#{version}/opendatactl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "dc91c0a99cd0d12a66d65c241e5ee7e022f730578dc4e031fd468f3c88b467d8"
      url "https://github.com/JungHoonGhae/opendatactl/releases/download/v#{version}/opendatactl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "93a7d054f65ff21a1350138c14096a87cfb0ffe30f7b558f7d24c3d1a15ea230"
      url "https://github.com/JungHoonGhae/opendatactl/releases/download/v#{version}/opendatactl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "de82f40eabcfb06568e0717f9c1d8f49cd77b73770ca9af3e308efb423e40537"
      url "https://github.com/JungHoonGhae/opendatactl/releases/download/v#{version}/opendatactl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "opendatactl"
  desc "data.go.kr 자연어 탐색부터 활용신청·승인 확인·실제 API 호출까지 잇는 AI 에이전트 워크플로"
  homepage "https://github.com/JungHoonGhae/opendatactl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "opendatactl"
  binary "gongctl"

  postflight do
    if OS.mac?
      ["opendatactl", "gongctl"].each do |binary|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{binary}"]
      end
    end
  end

  # No zap stanza required
end
